### ISSUE TITLE
Make wiki searchable

### ISSUE THREAD

**Issue by PetrilloAtWork** [SBNSoftware/SBNSoftware.github.io#2]
No idea if it's possible, and how.

**Comment by ikatza** [comment]
This is already possible using the search bar on the top left of GitHub. One of the main advantages over Redmine in my opinion. 

Going to this address:
https://github.com/SBNSoftware/SBNSoftware.github.io

![Screenshot 2020-07-20 at 9 51 09 PM](https://user-images.githubusercontent.com/8713617/87985219-2243cb80-cad3-11ea-8ce5-0c335d410ffc.png)

I'll add a link to that address on the top bar of the displayed wiki. I'll close this issue after I've done that.

**Comment by ikatza** [comment]
I have added a link to the GitHub repo on the top right of the navigation bar in 8274658, the GitHub logo.

![Screenshot 2020-07-21 at 2 54 12 PM](https://user-images.githubusercontent.com/8713617/88063553-0dfadf80-cb62-11ea-8599-85f1a733a275.png)
