### ISSUE TITLE
Quick link to edit pages

### ISSUE THREAD

**Issue by PetrilloAtWork** [SBNSoftware/SBNSoftware.github.io#3]
It would be very convenient to have a link in each wiki page that points to its GitHub source for fast editing.
If at all possible, that is.

**Comment by ikatza** [comment]
This is on my radar.

**Comment by ikatza** [comment]
I have added a link to the editable GitHub repo on the top right of the navigation bar in e5e6c0a, the _pencil Improve this page_

![Screenshot 2020-07-21 at 2 54 12 PM](https://user-images.githubusercontent.com/8713617/88063553-0dfadf80-cb62-11ea-8599-85f1a733a275.png)
